blogs/urls.py
from django.conf.urls import url

app_name = "blogs"


url_patterns = [
    url()
]

receipts/api/urls.py
from django.conf.urls import url

from .views import (
                    ReceiptAPIView,
                    # ReceipListSearchAPIView,
                    # ReceiptCreateAPIView,
                    # ReceiptDetailAPIView,
                    # ReceiptUpdateAPIView,
                    # ReceiptDeleteAPIView
                    )

urlpatterns = [
    url(r'^$',ReceiptAPIView.as_view()),
    # url(r'^create/$',ReceiptCreateAPIView.as_view()),
    # url(r'^(?P<id>\d+)/$',ReceiptDetailAPIView.as_view()),
    # url(r'^(?P<pk>\d+)/update/$', ReceiptUpdateAPIView.as_view()),
    # url(r'^(?P<pk>\d+)/delete/$', ReceiptDeleteAPIView.as_view()),
]

receipts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from receipts.views import *

app_name = 'receipts'

urlpatterns = [
    url(r'create_receipt/$', ReceiptsCreate.as_view(), name='create_receipt'),
    url('signup/$', sign_up_page, name='signUp'),
    url('signIn/$', sign_in_page, name='signIn'),
    url('blogs/$', blogs_page, name='blogs'),
    url(r'^(?P<pk>\d+)/$', ReceiptsDetailView.as_view(), name='detail'),
    url(r'^update/(?P<pk>\d+)/$', ReceiptsUpdate.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', ReceiptsDelete.as_view(), name='delete'),
    url(r'^list/$', ReceiptsListView.as_view(), name='list'),

]

receipts_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt

from receipts.views import index
from receipts_site.views import HomePage, TestPage, ThanksPage

urlpatterns = [
    url(r'^$', HomePage.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r"^test/$", TestPage.as_view(), name="test"),
    url(r'^receipts/', include('receipts.urls',namespace='receipts')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^thanks/$', ThanksPage.as_view(), name='thanks'),
    url(r'^receipts/api/',include('receipts.api.urls')),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/", include("groups.urls", namespace="groups")),
    # url(r"^groups/", include("groups.urls", namespace="groups")),
    # url(r"^posts/", include("posts.urls", namespace="posts"))
]

receipts/models.py
from django.conf import settings
from django.db import models
import PIL
from django.contrib import auth
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model, admin

# Create your models here.

User = get_user_model()


def upload_image(instance, filename):
    return "receipts/{user}/{filename}".format(user=instance.user, filename=filename)


class StatusQuerySet(models.QuerySet):
    pass

class ReceipManager(models.Manager):
    def get_queryset(self):
        return StatusQuerySet(self.model, using=self._db)

User = get_user_model()


class Receipts(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    title = models.CharField(max_length=32)
    content = models.CharField(max_length=256)
    ingredients = models.CharField(max_length=256)
    image_main = models.ImageField(upload_to=upload_image, null= True, blank=True)
    created_at = models.DateTimeField(auto_now=True)

    objects = ReceipManager()

    def __str__(self):
        return self.title

    def clean(self):
        super().clean()


    def get_absolute_url(self):
        return reverse("receipts:detail",kwargs={'pk':self.pk})
    # def get_absolute_url(self):
    #     return reverse('home')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["-created_at"]



class ReceiptSteps(models.Model):
    id_receipts = models.ForeignKey(Receipts)
    description = models.CharField(max_length=256)
    image = models.ImageField()


# class UserProfileInfo(models.Model):
#     user = models.OneToOneField(User)

receipts/forms.py
from django import forms
from .models import Receipts, ReceiptSteps


class ReceiptsForm(forms.ModelForm):
    class Meta:
        fields = ('title', 'content', 'ingredients', 'image_main')
        model = Receipts


    def clean_content(self, *args, **kwargs):
        content = self.cleaned_data.get('content')
        if len(content) > 240:
            raise forms.ValidationError('content is too long')
        return content

    def clean(self, *args, **kwargs):
        data = self.cleaned_data
        content = data.get('content', None)
        if content =="":
            content = None
        image = data.get("image", None)
        if content is None:# and image is None
            raise forms.ValidationError('content or image is required.')
        return super().clean(*args, **kwargs)

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["title"].label = "Загаловок"
        self.fields["content"].label = "Описание"
        self.fields["ingredients"].label = "Ингредиенты"
        self.fields["image_main"].label = "Картинка"



class ReceipStepsForm(forms.ModelForm):
    class Meta:
        fields = ()
        model = ReceiptSteps

receipts/api/views.py
from rest_framework import generics, mixins
from rest_framework.generics import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializer import ReceiptSerializer
from ..models import Receipts
import json


def is_json(json_data):
    try:
        real_json = json.loads(json_data)
        is_valid = True
    except ValueError:
        is_valid = False
    return is_valid

# class ReceipListSearchAPIView(APIView):
#     permission_classes = []
#     authentication_classes = []
#
#     def get(self, request, format=None):
#         qs = Receipts.objects.all()
#         serializer = ReceiptSerializer(data=qs, many=True)
#         json_data = serializer.data
#         return Response(json_data)
#
#     def post(self, request, format=None):
#         qs = Receipts.objects.all()
#         serializer = ReceiptSerializer(qs, many=True)
#         json_data = serializer.data
#         return Response(json_data)


class ReceiptAPIView(mixins.CreateModelMixin,
                     mixins.DestroyModelMixin,
                     mixins.UpdateModelMixin,
                     mixins.RetrieveModelMixin,
                     generics.ListAPIView):
    permission_classes = []
    authentication_classes = []
    # queryset = Receipts.objects.all()
    serializer_class = ReceiptSerializer

    def get_queryset(self):
        qs = Receipts.objects.all()
        query = self.request.GET.get('q')
        if query is not None:
            qs = qs.filter(content__icontains=query)
        return qs

    def get_object(self):
        request = self.request
        passed_id = request.GET.get("id", None)
        queryset = self.get_queryset()
        obj = None
        if passed_id is not None:
            obj = get_object_or_404(queryset, id=passed_id)
            self.check_object_permissions(request, obj)
        return obj

    def get(self, request, *args, **kwargs):
        url_passed_id = request.GET.get('id',None)
        json_data = {}
        body_ = request.body
        if is_json(body_):
            json_data = json.loads(request.body)
        new_passed_id = json_data.get('id',None)
        passed_id = url_passed_id or new_passed_id or None
        if passed_id is not None:
            return self.retrieve(request, *args, **kwargs)
        return super().get(request, *args, **kwargs)

    # def get(self, request, *args, **kwargs):
    #     passed_id = request.GET.get('id', None)
    #     if passed_id is not None:
    #         return self.retrieve(request, *args, **kwargs)
    #     return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

# class ReceiptCreateAPIView(generics.CreateAPIView):
#     permission_classes = []
#     authentication_classes = []
#     queryset = Receipts.objects.all()
#     serializer_class = ReceiptSerializer
#
#     # def perform_create(self, serializer):
#     #     serializer.save(user=self.request.user)
#
#
# class ReceiptDetailAPIView(generics.RetrieveAPIView):
#     permission_classes = []
#     authentication_classes = []
#     queryset = Receipts.objects.all()
#     serializer_class = ReceiptSerializer
#     lookup_field = 'id'
#
#     # def get_object(self,*args,**kwargs):
#     #     kwargs = self.kwargs
#     #     kw_id = kwargs.get('id')
#     #     return Receipts.objects.get(id=kw_id)
#
#
# class ReceiptUpdateAPIView(generics.UpdateAPIView):
#     permission_classes = []
#     authentication_classes = []
#     queryset = Receipts.objects.all()
#     serializer_class = ReceiptSerializer
#
#
# class ReceiptDeleteAPIView(generics.DestroyAPIView):
#     permission_classes = []
#     authentication_classes = []
#     queryset = Receipts.objects.all()
#     serializer_class = ReceiptSerializer

receipts/views.py
from django.shortcuts import render, render_to_response
from django.urls import reverse_lazy
from django.views.decorators.csrf import requires_csrf_token, csrf_exempt
from django.views.generic import View, DetailView, ListView, UpdateView, DeleteView, CreateView, TemplateView
from django.http import HttpResponse

from receipts.forms import ReceiptsForm
from .models import *

# Create your views here.

package_name = 'receipts'

from django.shortcuts import render


def upload_receipts_image(instance, filename):
    return "status/{user}/{filename}".format(user=instance.user, filename=filename)


@csrf_exempt
def index(request):
    if request.method == "POST":
        name = request.POST.get("name")
        # age = request.POST.get("age")     # получение значения поля age
        return HttpResponse("<h2>Hello, {0}</h2>".format(name))
    else:
        data = {'some_inf': 'jfdkasljdlkasjkl'}
        return render(request, f'{package_name}/index.html', context=data)


def sign_up_page(request):
    return render(request, f'{package_name}/sign_up_page.html')


def blogs_page(request):
    return render(request, f'{package_name}/blogs_page.html')


def sign_in_page(request):
    return render(request, f'{package_name}/sign_in_page.html')


class ReceiptsListView(ListView):
    model = Receipts
    template_name = 'receipts/receipts_list.html'
    context_object_name = 'receipts_list'


class ReceiptsDetailView(DetailView):
    model = Receipts
    template_name = 'receipts/receipts_detail.html'
    context_object_name = 'receipt_detail'


class ReceiptsDelete(DeleteView):
    model = Receipts
    success_url = reverse_lazy("receipts:list")
    context_object_name = 'receipt_delete'


class ReceiptsUpdate(UpdateView):
    model = Receipts
    fields = ("title","content")
    context_object_name = 'receipt_update'


class ReceiptsCreate(CreateView):
    # fields = ('title', 'content', 'ingredients', 'image_main')
    form_class = ReceiptsForm
    template_name = 'receipts/receipts_create.html'
    context_object_name = 'receipts_create'

receipts/templates/receipts/receipt_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

receipts/templates/receipts/receipt_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

receipts/templates/receipts/receipts_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
{% endblock %}
{% block body_block %}
<h1>Delete {{receipt_delete.title }}?</h1>
<div class="container">
    <!--Grid row-->
    <div class="row mt-5">
        <div class="col-md-6 mb-5 mt-md-0 mt-5 white-text text-center text-md-left">

            <hr class="hr-light wow fadeInLeft" data-wow-delay="0.3s">
            <form method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Delete">
                <a href="{% url 'receipts:detail' pk=receipt_delete.pk%} ">Отмена</a>

            </form>
        </div>
    </div>
</div>
{% endblock %}

receipts/templates/receipts/receipts_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block head_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
{% endblock %}
{% block body_block %}

<div class="view">
    <div class="mask rgba-gradient align-items-center">
        <!-- Content -->
        <div class="container">
            <!--Grid row-->
            <div class="row mt-5">
                <div class="col-md-6 mb-5 mt-md-0 mt-5 white-text text-center text-md-left">

                    <hr class="hr-light wow fadeInLeft" data-wow-delay="0.3s">
                    <form method="post">
                        {% csrf_token %}

                        {{ form|crispy }}
                        <button type="submit" class="btn btn-success">Создать</button>

                    </form>
                </div>

            </div>
        </div>
    </div>
</div>


{% endblock %}

receipts/templates/receipts/receipts_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
{% endblock %}
{% block body_block %}
        <div class="container">
            <!--Grid row-->
            <div class="row mt-5">
                <div class="col-md-6 mb-5 mt-md-0 mt-5 white-text text-center text-md-left">

                    <hr class="hr-light wow fadeInLeft" data-wow-delay="0.3s">
    <p>Name: {{receipt_detail.title}}</p>
    <p>Principal: {{receipt_detail.description}}</p>
    <p>Location: {{receipt_detail.ingredients}}</p>
    <p><a class='btn btn-warning' href="{% url 'receipts:update' pk=receipt_detail.pk %}">Update</a></p>
                </div>
            </div>
        </div>
{% endblock %}

receipts/templates/receipts/receipts_form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
{% endblock %}
{% block body_block %}
{% if not form.instance.pk %}
Create
{% else %}
Update
{% endif %}
<div class="container">
    <!--Grid row-->
    <div class="row mt-5">
        <div class="col-md-6 mb-5 mt-md-0 mt-5 white-text text-center text-md-left">

            <hr class="hr-light wow fadeInLeft" data-wow-delay="0.3s">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class='btn btn-primary' value="Submit">

            </form>
        </div>
    </div>
</div>
{% endblock %}

receipts/templates/receipts/receipts_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_block %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main1.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}"/>
{% endblock %}
{% block body_block %}
<!--<div class="container">-->
<!--&lt;!&ndash;Grid row&ndash;&gt;-->
<!--<div class="row mt-5">-->
<!--<div class="col-md-6 mb-5 mt-md-0 mt-5 white-text text-center text-md-left">-->

<!--<hr class="hr-light wow fadeInLeft" data-wow-delay="0.3s">-->
<!--<ol>-->
<main class="main">

    <div class="grid">
        {% for rec in receipts_list %}
        <!--<h2>-->
        <!--<li><a href="{% url 'receipts:detail' pk=rec.pk %}">{{rec.title}} </a></li>-->
        <!--</h2>-->
        <article class="card product-item">
            <header class="card__header">
                <h1 class="product__title">
                    {{ rec.title }}
                </h1>
            </header>
            <div class="card__image">
                <img src="{% static 'images_background/raspberries.jpg' %}"
                >
            </div>
            <div class="card__content">
                <h2 class="product__price">$
                    1000
                </h2>
                <p class="product__description">
                    {{ rec.content }}
                </p>
                <p>
                    {{ rec.ingredients }}
                </p>
            </div>
            <div class="card__actions">
                <a href="{% url 'receipts:detail' pk=rec.pk %}" class="btn">Детали</a>
                <!--<form action="/cart" method="POST">-->
                <!--<button class="btn" type="submit">Add to cart</button>-->
                <!--<input type="hidden" name="productId" value="<%= product.id %>">-->
                <!--</form>-->
            </div>
        </article>
        {% endfor %}
    </div>
</main>
<!--</ol>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->
{% endblock %}